// Database types for Slice 1 schema
// These will be auto-generated by Supabase CLI in production

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          display_name: string | null
          personalization: Json
          created_at: string
        }
        Insert: {
          id: string
          email: string
          display_name?: string | null
          personalization?: Json
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          display_name?: string | null
          personalization?: Json
          created_at?: string
        }
      }
      sessions: {
        Row: {
          id: string
          user_id: string | null
          title: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          title?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          title?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      messages: {
        Row: {
          id: string
          session_id: string | null
          role: 'user' | 'assistant' | 'system'
          content: string
          created_at: string
        }
        Insert: {
          id?: string
          session_id?: string | null
          role: 'user' | 'assistant' | 'system'
          content: string
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string | null
          role?: 'user' | 'assistant' | 'system'
          content?: string
          created_at?: string
        }
      }
      user_memory: {
        Row: {
          id: string
          user_id: string
          type: 'fact' | 'preference' | 'entity' | 'decision' | 'event' | 'insight' | 'concept'
          content: string
          embedding: string | null // pgvector stored as string representation
          confidence: number
          importance: number
          source_type: string
          source_session_id: string | null
          created_at: string
          last_accessed: string
          access_count: number
          superseded_by: string | null
          is_active: boolean
        }
        Insert: {
          id?: string
          user_id: string
          type: 'fact' | 'preference' | 'entity' | 'decision' | 'event' | 'insight' | 'concept'
          content: string
          embedding?: string | null // pgvector accepts string representation
          confidence?: number
          importance?: number
          source_type?: string
          source_session_id?: string | null
          created_at?: string
          last_accessed?: string
          access_count?: number
          superseded_by?: string | null
          is_active?: boolean
        }
        Update: {
          id?: string
          user_id?: string
          type?: 'fact' | 'preference' | 'entity' | 'decision' | 'event' | 'insight' | 'concept'
          content?: string
          embedding?: string | null
          confidence?: number
          importance?: number
          source_type?: string
          source_session_id?: string | null
          created_at?: string
          last_accessed?: string
          access_count?: number
          superseded_by?: string | null
          is_active?: boolean
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      search_memories: {
        Args: {
          query_embedding: string // pgvector string format: '[0.1,0.2,...]'
          match_user_id: string
          match_threshold?: number
          match_count?: number
        }
        Returns: {
          id: string
          type: 'fact' | 'preference' | 'entity' | 'decision' | 'event' | 'insight' | 'concept'
          content: string
          confidence: number
          importance: number
          similarity: number
        }[]
      }
      touch_memory: {
        Args: {
          memory_id: string
        }
        Returns: void
      }
      supersede_memory: {
        Args: {
          old_memory_id: string
          new_content: string
          new_embedding: string // pgvector string format
          new_importance?: number
        }
        Returns: string
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}

// Convenience types
export type Profile = Database['public']['Tables']['profiles']['Row']
export type Session = Database['public']['Tables']['sessions']['Row']
export type Message = Database['public']['Tables']['messages']['Row']

export type NewSession = Database['public']['Tables']['sessions']['Insert']
export type NewMessage = Database['public']['Tables']['messages']['Insert']

// Memory types (Slice 2)
export type MemoryType = 'fact' | 'preference' | 'entity' | 'decision' | 'event' | 'insight' | 'concept'

export type UserMemory = Database['public']['Tables']['user_memory']['Row']
export type NewUserMemory = Database['public']['Tables']['user_memory']['Insert']
export type UpdateUserMemory = Database['public']['Tables']['user_memory']['Update']
